# Generated by Django 4.1.1 on 2022-10-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_animal_remove_pessoa_ativa_delete_contato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(max_length=256, verbose_name='Nome'),
        ),
    ]
